[package]
name = "mqtt2file"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
paho-mqtt = { version = "0.11.1", default-features = false, features = ["bundled"] }
log = "0.4.17"
env_logger = "0.9.1"
hostname = "0.3.0"
ctrlc = "3.2.3"
anyhow = "1.0.65"
clap = { version = "4.0.14", features = ["derive"] }
chrono = "0.4.22"
crossbeam-channel = "0.5.6"
