[package]
name = "mqtt2file"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
paho-mqtt = { version = "0.12.1", default-features = false, features = ["bundled"] }
log = "0.4.20"
env_logger = "0.10.0"
hostname = "0.3.0"
ctrlc = "3.4.0"
anyhow = "1.0.75"
clap = { version = "4.4.1", features = ["derive"] }
chrono = "0.4.26"
crossbeam-channel = "0.5.8"
