[package]
name = "mqtt2file"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
paho-mqtt = { version = "0.12.3", default-features = false, features = ["bundled"] }
log = "0.4.20"
env_logger = "0.10.1"
hostname = "0.3.0"
ctrlc = "3.4.2"
anyhow = "1.0.79"
clap = { version = "4.4.14", features = ["derive"] }
chrono = "0.4.31"
crossbeam-channel = "0.5.11"
