[package]
name = "mqtt2file"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
paho-mqtt = { version = "0.11.1", default-features = false, features = ["bundled"] }
log = "0.4.17"
env_logger = "0.9.0"
hostname = "0.3.0"
ctrlc = "3.2.2"
anyhow = "1.0.58"
clap = { version = "3.2.8", features = ["derive"] }
chrono = "0.4.19"
crossbeam-channel = "0.5.5"
