[package]
name = "mqtt2file"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
paho-mqtt = { version = "0.12.0", default-features = false, features = ["bundled"] }
log = "0.4.17"
env_logger = "0.10.0"
hostname = "0.3.0"
ctrlc = "3.2.5"
anyhow = "1.0.69"
clap = { version = "4.1.9", features = ["derive"] }
chrono = "0.4.24"
crossbeam-channel = "0.5.7"
